name: Deploy to Environment

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Deploy to Environment
      env:
        NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
        NEXT_PUBLIC_API_BASE_URL: ${{ secrets.NEXT_PUBLIC_API_BASE_URL }}
      run: |
        if [ "${{ github.ref }}" == "refs/heads/main" ]; then
          echo "Deploying to production"
          # команда развертывания для прод
        elif [ "${{ github.ref }}" == "refs/heads/dev" ]; then
          echo "Deploying to development"
          # команда развертывания для дев
        fi
